### PR TITLE
Set TrafficStats tag in FirebaseInstallationServiceClient.createFirebaseInstallation

### LINKED ISSUE #2227: StrictMode UNTAGGED_SOCKET in FirebaseInstallationServiceClient
### [READ] Step 1: Are you in the right place?

yes. Issue in [FirebaseInstallationServiceClient](https://github.com/firebase/firebase-android-sdk/blob/e568cc0fd1b5b62826acd29ac084e27be983a7ce/firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java)

### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: N/A
  * Firebase Component: __firebase-installations__
  * Component version: __f30152eae2932bb2a540a95ffe81ec4d566b35da__ (HEAD [cl/336921685](http://cl/336921685))

#### Steps to reproduce:

1. Enable Strictmode
2. Start app that depends on firebase-installations

#### Relevant Code:

N/A

#### Logcat

```
java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2010)
at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
at libcore.io.IoBridge.socket(IoBridge.java:667)
at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
at java.net.Socket.createImpl(Socket.java:484)
at java.net.Socket.getImpl(Socket.java:547)
at java.net.Socket.setSoTimeout(Socket.java:1175)
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:226)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeFIDCreateRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:208)
at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:167)
at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:490)
at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:361)
at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:351)
at com.google.firebase.installations.FirebaseInstallations$$Lambda$3.run(Unknown Source:4)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```

### PR DESCRIPTION
**Pull request by regisd**
Fixes #2227

Tested:
I verified that com.google.googlequicksearchbox doesn't have the violation anymore in the e2e test.

Signed-off-by: Régis Décamps <regisd@google.com>

### CODE REVIEW

**Comment by regisd** [comment]
TrafficStats tags should be unique.
- [ ] *Googlers only* Let's wait for the change in [GmsNetworkClientTags.java](http://cs/GmsNetworkClientTags.java) [cl/347983675](http://cl/347983675)

Does GMS have emulator tests? Is there a way to check against StrictMode violations?

File: firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java [hunk 1]
```diff
@@ -56,6 +57,9 @@
  * @hide
  */
 public class FirebaseInstallationServiceClient {
+
+  public static final int CREATE_INSTALLATION_TRAFFIC_STATS_TAG = 0x00008000;
```
Comment (ankitaj224) [inline firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java:61]: Thanks @regisd for fixing this up. I had some questions:

We have some other http requests that are made in this class. 

- Do we need stats_tag's for each of those as well?
- If yes, can we reuse the same stats tag? Or do we unique one's? And should we reserve them just like you did in cl/348055557

Like GenerateToken & Delete.

**Review by ankitaj224 — APPROVED** [review]

File: firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java (hunk 1 above)
Comment (regisd) [reply firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java:61]: Ah good point! Indeed, all http connections need to be tagged.

The initial cl/348055557 reserves a whole range in Firebase common. For more fine-grained tagging, we can use "Secondary tags".

Comment (regisd) [reply firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java]: Added the secondary tags in cl/351113253. Since the primary tag is reserved for firebase-installations, I don't think there is a requirement in the order of submission of the CL and the PR.

**Comment by regisd** [comment]
I've added tagging on all `url.openConnection()` in firebase-installations.
PTAL (in conjunction with cl/351113253 and feel free to squash submit).

**Comment by ankitaj224** [comment]
Thank you so much @regisd
