### PR TITLE
[AI] Attach X-Firebase-AppCheck header on Live API WebSocket handshake

### LINKED ISSUE #8060: firebase-ai: LiveGenerativeModel.connect() WebSocket does not attach X-Firebase-AppCheck header
### Environment

* Firebase Component: AI Logic (`firebase-ai`)
* Component version: 17.11.0 (via firebase-bom 34.12.0); also present on `main` as of today.

### Problem

When App Check is enforced on `firebasevertexai.googleapis.com`, Gemini Live sessions fail with:

```
ServiceConnectionHandshakeFailedException: Channel was closed by the server. Details: Firebase App Check token is invalid.
```

HTTPS methods on the same `FirebaseAI` instance (`generateContent`, `generateContentStream`, `countTokens`) succeed with identical App Check setup. Only the Live API path (`liveModel().connect()`) fails.

Looking at [`APIController.kt:258-259`](https://github.com/firebase/firebase-android-sdk/blob/main/ai-logic/firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt#L258-L259):

```kotlin
suspend fun getWebSocketSession(location: String): DefaultClientWebSocketSession =
  client.webSocketSession(getBidiEndpoint(location)) { applyCommonHeaders() }
```

The WebSocket config lambda calls only `applyCommonHeaders()`. It does not call `applyHeaderProvider()`, which is what sets the `X-Firebase-AppCheck` header (via `AppCheckHeaderProvider.generateHeaders()`). Other methods like `countTokens` (line 273) correctly call both.

Result: WebSocket upgrade request is sent without an App Check token, so the server rejects it.

### Steps to reproduce

1. Enable App Check enforcement on `firebasevertexai.googleapis.com`.
2. Install a provider factory at startup:
   ```kotlin
   Firebase.appCheck.installAppCheckProviderFactory(PlayIntegrityAppCheckProviderFactory.getInstance())
   ```
3. Call Live API:
   ```kotlin
   FirebaseAI.getInstance(
       backend = GenerativeBackend.vertexAI("us-central1"),
       useLimitedUseAppCheckTokens = true
   ).liveModel("gemini-live-2.5-flash-native-audio").connect()
   ```
4. Observe `ServiceConnectionHandshakeFailedException: ... App Check token is invalid.`
5. Confirm `generativeModel(...).generateContentStream(...)` works on the same setup.

### PR DESCRIPTION
**Pull request by jacksonej**
Fixes #8060

## Summary

`APIController.getWebSocketSession()` did not call `applyHeaderProvider()`, so the `X-Firebase-AppCheck` header was missing from the WebSocket upgrade request. This broke Gemini Live whenever App Check was enforced on AI Logic, while HTTPS methods on the same class continued to work because they route through either `applyHeaderProvider()` directly or `postStream` (which calls it internally).

## Fix

`applyHeaderProvider()` is `suspend` and Ktor's `webSocketSession { }` config lambda is non-suspend, so the fix pre-fetches headers in the outer suspend context and applies them synchronously inside the lambda.

## Test plan

- [x] Added unit test `headers from HeaderProvider are added to the WebSocket handshake` mirroring the existing HTTP-path test — passes.
- [x] Existing `RequestFormatTests` suite still passes (`./gradlew :ai-logic:firebase-ai:test`).
- [x] Code formatted with `./gradlew :ai-logic:firebase-ai:spotlessApply`.
- [x] Manual E2E reproduction: built the SDK locally, consumed via `mavenLocal()` in a real app, confirmed `liveModel().connect()` succeeds with App Check enforced on AI Logic.

### CODE REVIEW

**Review by VinayGuthal — DISMISSED** [review]

File: ai-logic/firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt [hunk 1]
```diff
@@ -255,8 +255,17 @@ internal constructor(
         "wss://firebasevertexai.googleapis.com/ws/google.firebase.vertexai.v1beta.GenerativeService/BidiGenerateContent?key=$key"
     }
 
-  suspend fun getWebSocketSession(location: String): DefaultClientWebSocketSession =
-    client.webSocketSession(getBidiEndpoint(location)) { applyCommonHeaders() }
+  suspend fun getWebSocketSession(location: String): DefaultClientWebSocketSession {
```
Comment (rlazo) [inline ai-logic/firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt:258]: The `fun HttpRequestBuilder.applyHeaderProvider()` includes a `withTimeout` block that's important, in case the header providers take too long. 

We can abstract this by splitting the extraction and application

```
  private suspend fun HttpRequestBuilder.applyHeaderProvider() {
    for ((tag, value) in extractHeaders(headerProvider)) {
      header(tag, value)
    }
  }

  private suspend fun extractHeaders(headerProvider: HeaderProvider?): Map<String, String> {
    if (headerProvider == null)
      return emptyMap()
    try {
      return withTimeout(headerProvider.timeout) {
        headerProvider.generateHeaders()
      }
    } catch (e: TimeoutCancellationException) {
      Log.w(TAG, "HeaderProvided timed out without generating headers, ignoring", e)
      return emptyMap()
    }
  }
``

then the code here can use the `extractHeaders` method to get them, including timeout management, without duplicating code.

**Review by rlazo — CHANGES_REQUESTED** [review]

File: ai-logic/firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt (hunk 1 above)
Comment (jacksonej) [reply ai-logic/firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt:258]: Addressed by extracting the timeout-protected fetch into a shared extractHeaders() helper.

**Review by rlazo — APPROVED** [review]

**Comment by rlazo** [comment]
Thanks a lot for your contribution @jacksonej ! It will be included in the next release of the SDK.
