### PR TITLE
Trying to fix issue #72 - Targeting Android 28, with Android Studio 3.2.1 

### LINKED ISSUE #72: Migrate to Android 28
Since now we have Android 28, with the latest Gradle plugin, why don't we just use the latest dependencies?

### PR DESCRIPTION
**Pull request by iamyaoxi**
Fixes #72

### CODE REVIEW

**Comment by samtstern** [comment]
I have not reviewed this for functionality in here, but there's nothing malicious.
/ok-to-test

**Comment by iamyaoxi** [comment]
Finally it went through. 
@samstern what do you think of this PR?

File: buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy [hunk 1]
```diff
@@ -98,7 +98,7 @@ class LicenseResolverPlugin implements Plugin<Project> {
 
                 // must run before preBuild, otherwise it produces an empty license report.
                 project.tasks.getByName('preBuild').mustRunAfter licensesTask
-                project.tasks.getByName("bundle${variantName}") {
+                project.tasks.getByName("bundle${variantName}Aar") {
```
Comment (samtstern) [inline buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy]: @ashwinraghav can you sanity check this?
@iamyaoxi can you explain this change?  Is this something to do with the newer gradle plugin?

File: firebase-common/firebase-common.gradle [hunk 2]
```diff
@@ -45,8 +46,8 @@ android {
         }
     }
     compileOptions {
-        sourceCompatibility JavaVersion.VERSION_1_8
-        targetCompatibility JavaVersion.VERSION_1_8
+        sourceCompatibility 1.8
```
Comment (samtstern) [inline firebase-common/firebase-common.gradle]: Any reason not to use `JavaVersion` constants?

File: firebase-database-collection/firebase-database-collection.gradle [hunk 3]
```diff
@@ -14,13 +14,41 @@
...
 
-def androidVersion = 26
+def androidVersion = 28
 
 android {
     compileSdkVersion androidVersion
+    defaultConfig {
+        minSdkVersion 14
+    }
+    buildTypes {
```
Comment (samtstern) [inline firebase-database-collection/firebase-database-collection.gradle]: These lines look a little suspicious:

- Do we need the empty `sourceSets`?
- Shouldn't the `compileOptions` be inherited?
- I don't think we want `useProguard true` anymore, we're not proguarding these SDKs going forward.  Or is that only needed to pass forward the `consumerProguardFiles`?

File: test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java [hunk 4]
```diff
@@ -81,15 +82,11 @@ public void onCancelled(DatabaseError error) {
     auth.signOut();
     auth.signInWithEmailAndPassword("test@mailinator.com", "password")
         .addOnSuccessListener(
-            new OnSuccessListener<AuthResult>() {
-              @Override
-              public void onSuccess(AuthResult authResult) {
+            authResult ->
```
Comment (samtstern) [inline test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java]: nit: strange indentation here, `authResult` is indented left of `public`...

File: buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy (hunk 1 above)
Comment (iamyaoxi) [reply buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy]: Yes. I think it's related to the newer Gradle plugin. I tried to use bundle${variantName} task, it always failing. And I read it's already replaced with bundleAar

File: test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java (hunk 4 above)
Comment (iamyaoxi) [reply test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java]: Okay. I was thinking maybe we can use lambda features since test-app now use Java 8.

Comment (samtstern) [reply test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java]: I'm not sure if we can use lambda (I don't see why not) I was just saying it looks like you need to move authResult in a few columns.  Not a big deal!

File: buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy (hunk 1 above)
Comment (samtstern) [reply buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy]: SGTM

File: firebase-database-collection/firebase-database-collection.gradle (hunk 3 above)
Comment (iamyaoxi) [reply firebase-database-collection/firebase-database-collection.gradle]: - `compileOptions` is not inherited. It always failed when I didn't set it to Java 8.
- I only follow pattern of other projects for the use of `useProguard true`. So should we remove it, as well in other projects?

File: test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java (hunk 4 above)
Comment (iamyaoxi) [reply test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java]: Hmm.. I was using google-java-format as indent format for this file. And whenever I reformat, it goes like this. I don't know. Should I disable it?

File: firebase-database-collection/firebase-database-collection.gradle (hunk 3 above)
Comment (samtstern) [reply firebase-database-collection/firebase-database-collection.gradle]: @ashwinraghav ?

File: test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java (hunk 4 above)
Comment (samtstern) [reply test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java]: Nope!  `google-java-format` is smarter than I am

File: buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy (hunk 1 above)
Comment (iamyaoxi) [reply buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy]: :)

**Comment by iamyaoxi** [comment]
I find it weird for it to fail on something different. Try again.

/retest

File: firebase-database-collection/firebase-database-collection.gradle [hunk 5]
```diff
@@ -14,13 +14,29 @@
...
+        targetCompatibility JavaVersion.VERSION_1_8
+    }
 }
 
 dependencies {
-    testCompile 'junit:junit:4.11'
-    testCompile 'net.java:quickcheck:0.6'
+    testImplementation 'junit:junit:4.12'
+    testImplementation 'net.java:quickcheck:0.6'
+    testAnnotationProcessor 'net.java:quickcheck-src-generator:0.6'
```
Comment (ashwinraghav) [inline firebase-database-collection/firebase-database-collection.gradle]: Can you speak more to why these are necessary?

File: firebase-database/firebase-database.gradle [hunk 6]
```diff
@@ -86,20 +83,23 @@ dependencies {
...
     androidTestImplementation 'com.android.support.test:runner:1.0.2'
-    androidTestImplementation 'com.google.truth:truth:0.39'
+    androidTestImplementation 'com.google.truth:truth:0.42'
     androidTestImplementation 'com.fasterxml.jackson.core:jackson-core:2.9.6'
     androidTestImplementation 'com.fasterxml.jackson.core:jackson-databind:2.9.6'
     androidTestImplementation 'junit:junit:4.12'
-    androidTestImplementation 'net.java.quickcheck:quickcheck:0.6'
+    androidTestImplementation 'net.java:quickcheck:0.6'
+    androidTestAnnotationProcessor 'net.java:quickcheck-src-generator:0.6'
+    androidTestAnnotationProcessor 'net.java.quickcheck:quickcheck-src-generator:0.6'
```
Comment (ashwinraghav) [inline firebase-database/firebase-database.gradle]: Ditto

Comment (iamyaoxi) [reply firebase-database/firebase-database.gradle]: Same as above. But this time, somehow Gradle needs 2 of these `annotationProcessor` to be devlared explicitly. Or else it will fail. I'm still wondering why, I think there's an inconsistency with `quickcheck` dependency in using the annotationProcessor.

File: test-apps/firestore-test-app/build.gradle [hunk 7]
```diff
@@ -33,6 +33,11 @@ android {
         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
     }
 
+    compileOptions {
```
[the remark this answers is not in the document]
Comment (iamyaoxi) [reply test-apps/firestore-test-app/build.gradle]: I see. I was thinking since Android gradle plugin >3.0 will allow all apps to use Java8 without retrolambda, might as well just use Java 8.

File: firebase-database-collection/firebase-database-collection.gradle [hunk 8]
```diff
@@ -14,13 +14,29 @@
 
 apply plugin: 'com.android.library'
 
-def androidVersion = 26
+def androidVersion = 28
 
 android {
     compileSdkVersion androidVersion
+    defaultConfig {
+        minSdkVersion 14
```
[the remark this answers is not in the document]
Comment (iamyaoxi) [reply firebase-database-collection/firebase-database-collection.gradle]: Hmm... It should be possible. But I was thinking why we have to use minSdkVersion 9? Isn't it too old? Android Support library minSdkVersion is 14.

File: firebase-database/firebase-database.gradle (hunk 6 above)
Comment (iamyaoxi) [reply firebase-database/firebase-database.gradle]: After some times of experimenting, I guess it's not failing. But somehow, often times the CI system will treat this as error and failing the build. What do you think @ashwinraghav ?

File: firebase-database-collection/firebase-database-collection.gradle (hunk 8 above)
[the remark this answers is not in the document]
Comment (iamyaoxi) [reply firebase-database-collection/firebase-database-collection.gradle]: Preserved to 9. Resolved.

File: firebase-database/firebase-database.gradle (hunk 6 above)
Comment (iamyaoxi) [reply firebase-database/firebase-database.gradle]: Backlog references: 
- Failed in `check` process. https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/73/check/1052633649951805440/
- This build requires annotationProcessor for butterknife. But after `retest` works again.
https://k8s-gubernator.appspot.com/build/android-ci/pr-logs/pull/firebase_firebase-android-sdk/73/connected-check/1056156782134562817/

**Comment by samtstern** [comment]
@iamyaoxi thanks for all the hard work and patience!

**Comment by iamyaoxi** [comment]
Thank you @samtstern and @ashwinraghav 

I'll do my best to keep on contributing, and hopefully can give more meaningful contributions! :)
